### ISSUE TITLE
Failed to activate the output-panel package

### ISSUE THREAD

**Issue by omcecil** [31i73/atom-output-panel#5]
[Enter steps to reproduce:]

1. output-panel fails to activate upon starting atom

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise 2015 LTSB
**Thrown From**: [output-panel](https://github.com/31i73/atom-output-panel) package 0.3.0

### Stack Trace

Failed to activate the output-panel package

```
At open() not supported on windows, use Fork() instead.

Error: open() not supported on windows, use Fork() instead.
    at Function.WindowsTerminal.open (/packages/output-panel/node_modules/node-pty/lib/windowsTerminal.js:77:15)
    at Object.open (/packages/output-panel/node_modules/node-pty/lib/index.js:27:21)
    at Object.activate (/packages/output-panel/lib/main.coffee:69:22)
    at Package.module.exports.Package.activateNow (<embedded>:68279:25)
    at <embedded>:68251:38
    at Package.module.exports.Package.measure (<embedded>:68125:21)
    at <embedded>:68244:32
    at Package.module.exports.Package.activate (<embedded>:68241:40)
    at PackageManager.module.exports.PackageManager.activatePackage (<embedded>:20426:40)
    at <embedded>:20407:35
    at Config.module.exports.Config.transactAsync (<embedded>:17500:24)
    at PackageManager.module.exports.PackageManager.activatePackages (<embedded>:20402:25)
    at PackageManager.module.exports.PackageManager.activate (<embedded>:20384:52)
    at <embedded>:1085:34

```

### Commands

```
```

### Non-Core Packages

```
atom-debugger 0.1.6 
atom-package-sync 0.2.5 
build 0.68.0 
build-cmake 0.9.1 
build-gradle 0.6.0 
build-make 0.13.0 
busy 0.7.0 
busy-signal 1.4.1 
dbg 1.6.1 
dbg-gdb 1.7.3 
intentions 1.1.2 
language-cmake 0.3.0 
language-fortran 2.1.0 
linter 2.1.4 
linter-gfortran 0.5.0 
linter-ui-default 1.6.0 
output-panel 0.3.0 
platformio-ide-terminal 2.5.1 
```

**Comment by ProPuke** [comment]
Ouch. Seems the current tty solution is incomplete on windows.

I've disabled interactive sessions on windows and set dbg-gdb to spawn a separate interactive console window for now. It's ugly, but it's perhaps better than not having interaction at all on windows. (Also vscode seems to use the same ugly hack with gdb, so I don't feel *quite* as dirty)
