### ISSUE TITLE
Failed to update output-panel to 0.3.2

### ISSUE THREAD

**Issue by riophae** [31i73/atom-output-panel#6]
This output is as follows:

```
> node-pty@0.6.6 install C:\Users\riophae\AppData\Local\Temp\apm-install-dir-117512-16048-14quqqj.xrs14z33di\node_modules\output-panel\node_modules\node-pty
> node scripts/install.js


C:\Users\riophae\AppData\Local\Temp\apm-install-dir-117512-16048-14quqqj.xrs14z33di\node_modules\output-panel\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Users\riophae\AppData\Local\atom\app-1.17.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\riophae\AppData\Local\atom\app-1.17.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\riophae\AppData\Local\Temp\apm-install-dir-117512-16048-14quqqj.xrs14z33di\node_modules\output-panel\node_modules\node-pty\build\binding.sln]
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ��������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\Users\riophae\AppData\Local\Temp\apm-install-dir-117512-16048-14quqqj.xrs14z33di\node_modules\output-panel\node_modules\node-pty\build\binding.sln]
C:\Users\riophae\AppData\Local\Temp\apm-install-dir-117512-16048-14quqqj.xrs14z33di
`-- (empty)


gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\riophae\AppData\Local\atom\app-1.17.2\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\riophae\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\riophae\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\riophae\AppData\Local\Temp\apm-install-dir-117512-16048-14quqqj.xrs14z33di\node_modules\output-panel\node_modules\node-pty
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\riophae\AppData\Local\Temp\apm-install-dir-117512-16048-14quqqj.xrs14z33di\package.json'
npm WARN apm-install-dir-117512-16048-14quqqj.xrs14z33di No description
npm WARN apm-install-dir-117512-16048-14quqqj.xrs14z33di No repository field.
npm WARN apm-install-dir-117512-16048-14quqqj.xrs14z33di No README data
npm WARN apm-install-dir-117512-16048-14quqqj.xrs14z33di No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Users\\riophae\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\riophae\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\riophae\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\riophae\\.atom\\.apmrc" "install" "C:\\Users\\riophae\\AppData\\Local\\Temp\\d-117512-16048-q3seep.gtd0vhd7vi\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=ia32" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! node-pty@0.6.6 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.6.6 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\riophae\AppData\Local\Temp\apm-install-dir-117512-16048-14quqqj.xrs14z33di\npm-debug.log
npm ERR! code 1
```

**Comment by ProPuke** [comment]
Hi, let me know if it updates okay now

**Comment by riophae** [comment]
Thank you very much!
However, I was experiencing the same issue as #8.
